import os
import shutil
import subprocess
import warnings
from tempfile import TemporaryDirectory
from unittest import TestCase, skipUnless

from bauh.gems.arch.worker import RE_COMPRESS_MULTITHREAD, ArchCompilationOptimizer


class CompressMultithreadDetectionTest(TestCase):
    """Deteccion de COMPRESSXZ/COMPRESSZST ya multihilo (F77)."""

    @classmethod
    def setUpClass(cls):
        warnings.filterwarnings('ignore', category=DeprecationWarning)

    def test_detects_the_arch_default_zstd_definition(self):
        self.assertTrue(RE_COMPRESS_MULTITHREAD.search('COMPRESSZST=(zstd -c -T0 -)'))

    def test_detects_a_customized_zstd_definition(self):
        self.assertTrue(RE_COMPRESS_MULTITHREAD.search('COMPRESSZST=(zstd -c -T0 --ultra -20 -)'))

    def test_detects_the_long_option(self):
        self.assertTrue(RE_COMPRESS_MULTITHREAD.search('COMPRESSXZ=(xz -c -z - --threads=0)'))

    def test_detects_a_spaced_thread_option(self):
        self.assertTrue(RE_COMPRESS_MULTITHREAD.search('COMPRESSXZ=(xz -c -z -T 4 -)'))

    def test_does_not_detect_a_single_threaded_definition(self):
        self.assertFalse(RE_COMPRESS_MULTITHREAD.search('COMPRESSXZ=(xz -c -z -)'))
        self.assertFalse(RE_COMPRESS_MULTITHREAD.search('COMPRESSZST=(zstd -c -z -q -)'))


class CustomMakepkgGenerationTest(TestCase):
    """makepkg.conf optimizado que no descarta la configuracion externa (F35)."""

    @classmethod
    def setUpClass(cls):
        warnings.filterwarnings('ignore', category=DeprecationWarning)

    def test_gen_external_config_sourcing__loads_the_distribution_and_user_files(self):
        sourcing = ArchCompilationOptimizer.gen_external_config_sourcing()

        self.assertIn('/etc/makepkg.conf.d/*.conf', sourcing)
        self.assertIn('${XDG_CONFIG_HOME:-$HOME/.config}/pacman/makepkg.conf', sourcing)
        self.assertIn('$HOME/.makepkg.conf', sourcing)

    def test_guard_optimization__protects_the_stripped_variables(self):
        for declaration, var in (('MAKEFLAGS="-j$(nproc)"', 'MAKEFLAGS'),
                                 ('COMPRESSXZ=(xz -c -z - --threads=0)', 'COMPRESSXZ'),
                                 ('COMPRESSZST=(zstd -c -z -q - --threads=0)', 'COMPRESSZST')):
            with self.subTest(var=var):
                guarded = ArchCompilationOptimizer.guard_optimization(declaration)
                self.assertIn(f'if [ -z "${{{var}[*]}}" ]; then', guarded)
                self.assertIn(declaration, guarded)

    def test_guard_optimization__leaves_buildenv_untouched(self):
        declaration = 'BUILDENV=(ccache color !sign)'
        self.assertEqual(declaration, ArchCompilationOptimizer.guard_optimization(declaration))

    def test_gen_custom_makepkg_content__keeps_the_original_content_and_the_marker(self):
        content = ArchCompilationOptimizer.gen_custom_makepkg_content('CFLAGS="-O2"\n',
                                                                      ['MAKEFLAGS="-j$(nproc)"'])

        self.assertIn('CFLAGS="-O2"', content)
        self.assertIn('# <generated by bauh>', content)
        # la carga de la configuracion externa debe ir antes de las optimizaciones
        self.assertLess(content.index('/etc/makepkg.conf.d'), content.index('# <generated by bauh>'))

    @staticmethod
    def _source(conf_path: str, home: str, echo: str) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env['HOME'] = home
        env.pop('XDG_CONFIG_HOME', None)

        return subprocess.run(['bash', '-c', f'source "{conf_path}"; {echo}'],
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=env, check=False)

    @skipUnless(shutil.which('bash') is not None, 'bash no disponible')
    def test_gen_custom_makepkg_content__is_valid_bash(self):
        content = ArchCompilationOptimizer.gen_custom_makepkg_content(
            'CFLAGS="-O2"\nCXXFLAGS="-O2"\n',
            ['MAKEFLAGS="-j$(nproc)"', 'COMPRESSZST=(zstd -c -z -q - --threads=0)', 'BUILDENV=(ccache color)'])

        with TemporaryDirectory() as temp_dir:
            conf_path = f'{temp_dir}/makepkg.conf'

            with open(conf_path, 'w') as f:
                f.write(content)

            res = subprocess.run(['bash', '-n', conf_path], stdout=subprocess.PIPE,
                                 stderr=subprocess.STDOUT, check=False)

            self.assertEqual(0, res.returncode, res.stdout.decode())

    @skipUnless(shutil.which('bash') is not None, 'bash no disponible')
    def test_gen_custom_makepkg_content__the_user_definition_wins(self):
        with TemporaryDirectory() as temp_dir:
            conf_dir = f'{temp_dir}/makepkg.conf.d'
            os.makedirs(conf_dir)

            home = f'{temp_dir}/home'
            os.makedirs(f'{home}/.config/pacman')

            with open(f'{home}/.config/pacman/makepkg.conf', 'w') as f:
                f.write('MAKEFLAGS="-j2"\nPACKAGER="yo <yo@example.org>"\n')

            conf_path = f'{temp_dir}/makepkg.conf'

            with open(conf_path, 'w') as f:
                f.write(ArchCompilationOptimizer.gen_custom_makepkg_content('CFLAGS="-O2"\n',
                                                                            ['MAKEFLAGS="-j$(nproc)"'],
                                                                            conf_dir=conf_dir))

            res = self._source(conf_path, home, 'echo "MAKEFLAGS=$MAKEFLAGS"; echo "PACKAGER=$PACKAGER"')

            output = res.stdout.decode()
            self.assertEqual(0, res.returncode, output)
            self.assertIn('MAKEFLAGS=-j2', output)
            self.assertIn('PACKAGER=yo <yo@example.org>', output)

    @skipUnless(shutil.which('bash') is not None, 'bash no disponible')
    def test_gen_custom_makepkg_content__the_distribution_files_are_loaded(self):
        with TemporaryDirectory() as temp_dir:
            conf_dir = f'{temp_dir}/makepkg.conf.d'
            os.makedirs(conf_dir)

            with open(f'{conf_dir}/rust.conf', 'w') as f:
                f.write('RUSTFLAGS="-Copt-level=3"\n')

            home = f'{temp_dir}/home'
            os.makedirs(home)

            conf_path = f'{temp_dir}/makepkg.conf'

            with open(conf_path, 'w') as f:
                f.write(ArchCompilationOptimizer.gen_custom_makepkg_content('CFLAGS="-O2"\n',
                                                                            ['MAKEFLAGS="-j7"'],
                                                                            conf_dir=conf_dir))

            res = self._source(conf_path, home, 'echo "RUSTFLAGS=$RUSTFLAGS"')

            output = res.stdout.decode()
            self.assertEqual(0, res.returncode, output)
            self.assertIn('RUSTFLAGS=-Copt-level=3', output)

    @skipUnless(shutil.which('bash') is not None, 'bash no disponible')
    def test_gen_custom_makepkg_content__the_optimization_applies_when_nothing_defines_it(self):
        with TemporaryDirectory() as temp_dir:
            conf_dir = f'{temp_dir}/makepkg.conf.d'
            os.makedirs(conf_dir)

            home = f'{temp_dir}/home'
            os.makedirs(home)

            conf_path = f'{temp_dir}/makepkg.conf'

            with open(conf_path, 'w') as f:
                f.write(ArchCompilationOptimizer.gen_custom_makepkg_content('CFLAGS="-O2"\n',
                                                                            ['MAKEFLAGS="-j7"'],
                                                                            conf_dir=conf_dir))

            res = self._source(conf_path, home, 'echo "MAKEFLAGS=$MAKEFLAGS"')

            output = res.stdout.decode()
            self.assertEqual(0, res.returncode, output)
            self.assertIn('MAKEFLAGS=-j7', output)
